=== Jadro007/BarUTomaDataAnalyst/database/admin.xsd
<?xml version="1.0"?>

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

<!--

ADMIN-SCHEMA
<admin admin_id="">
  <date value="">
    <bar bar_id="">
      <income/>
      <alcohol/>
      <drinks>
        <drink name="">sold-count</drink>
      </drinks>
      <ingredients>
        <ingredient name="" amount="">used-count</ingredient>
      </ingredients>
    </bar>
  </date>
</admin>


- u xs:element je minOccurs="1" maxOccurs="1" vzdy default
-->

    <!-- Simple data types -->
    <xs:simpleType name="idInteger">
        <xs:restriction base="xs:integer">
            <xs:totalDigits value="10"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="nonEmptyString">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="simpleDecimal">        <!-- jednoduchy nenulovy decimal s dvemi desetinnymi misty -->
        <xs:restriction base="xs:decimal">
            <xs:minExclusive value="0"/>
            <xs:pattern value="\d+\.\d{2}"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Schema -->
    <xs:element name="data">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="admin" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="date" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="bar" minOccurs="1" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="income" type="simpleDecimal"/>
                                                    <xs:element name="alcohol" type="simpleDecimal"/>
                                                    <xs:element name="drinks">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="drink" maxOccurs="unbounded">
                                                                    <xs:complexType>
                                                                        <xs:simpleContent>
                                                                            <xs:extension base="xs:integer">
                                                                                <xs:attribute name="name" use="required" type="nonEmptyString"/>
                                                                            </xs:extension>
                                                                        </xs:simpleContent>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="ingredients" minOccurs="0" maxOccurs="1">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="ingredient" maxOccurs="unbounded">
                                                                    <xs:complexType>
                                                                        <xs:simpleContent>
                                                                            <xs:extension base="xs:integer">
                                                                                <xs:attribute name="amount" type="simpleDecimal" use="required"/>
                                                                                <xs:attribute name="name" type="nonEmptyString" use="required"/>
                                                                            </xs:extension>
                                                                        </xs:simpleContent>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="bar_id" type="idInteger" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="value" type="xs:date" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="admin_id" type="idInteger" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Jadro007/BarUTomaDataAnalyst/database/admin-example.xml
<?xml version="1.0" encoding="UTF-8"?>

<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="admin.xsd">
    <admin admin_id="1">
        <date value="2015-05-14">
            <bar bar_id="1">
                <income>340.00</income>     <!-- jak se bude pocitat celkova cena? -->
                <alcohol>0.24</alcohol>     <!-- 4x rum + 2x jager -->
                <drinks>
                    <drink name="Cuba Libre">4</drink>
                    <drink name="Jägerbomb">2</drink>
                </drinks>
                <ingredients>
                    <ingredient amount="0.04" name="rum">4</ingredient>     <!-- 4cl -->
                    <ingredient amount="0.10" name="cola">4</ingredient>    <!-- 10cl -->
                    <ingredient amount="1.00" name="lime">2</ingredient>    <!-- ks -->
                    <ingredient amount="0.04" name="jagermeister">2</ingredient>
                    <ingredient amount="0.25" name="red bull">2</ingredient>
                    <ingredient amount="1.00" name="ice cube">12</ingredient>
                </ingredients>
            </bar>
        </date>
        <date value="2015-05-16">
            <bar bar_id="1">
                <income>290.00</income>
                <alcohol>0.28</alcohol>
                <drinks>
                    <drink name="Margarita">3</drink>
                    <drink name="Gin and Tonic">2</drink>
                </drinks>
                <ingredients>
                    <ingredient amount="0.04" name="tequilla">3</ingredient>
                    <ingredient amount="0.02" name="lime juice">3</ingredient>
                    <ingredient amount="0.02" name="cointreau">3</ingredient>
                    <ingredient amount="0.05" name="gin">2</ingredient>
                    <ingredient amount="0.10" name="tonic">2</ingredient>
                    <ingredient amount="1.00" name="lemon">2</ingredient>
                    <ingredient amount="1.00" name="ice cube">10</ingredient>
                </ingredients>
            </bar>
            <bar bar_id="2">
                <income>160.00</income>
                <alcohol>0.16</alcohol>
                <drinks>
                    <drink name="Jameson on the Rocks">4</drink>
                </drinks>
                <ingredients>
                    <ingredient amount="0.04" name="jameson">4</ingredient>
                    <ingredient amount="1.00" name="ice cube">12</ingredient>
                </ingredients>
            </bar>
        </date>
    </admin>
    <admin admin_id="2">
        <date value="2015-05-14">
            <bar bar_id="2">
                <income>120.00</income>
                <alcohol>0.08</alcohol>
                <drinks>
                    <drink name="Cuba Libre">2</drink>
                </drinks>
                <ingredients>
                    <ingredient amount="0.04" name="rum">2</ingredient>
                    <ingredient amount="0.10" name="cola">2</ingredient>
                    <ingredient amount="1.00" name="lime">1</ingredient>
                    <ingredient amount="1.00" name="ice cube">4</ingredient>
                </ingredients>
            </bar>
        </date>
        <date value="2015-05-15">
            <bar bar_id="1">
                <income>1030.00</income>
                <alcohol>0.62</alcohol>
                <drinks>
                    <drink name="Gin and Tonic">2</drink>
                    <drink name="Jägerbomb">13</drink>
                </drinks>
                <ingredients>
                    <ingredient amount="0.05" name="gin">2</ingredient>
                    <ingredient amount="0.10" name="tonic">2</ingredient>
                    <ingredient amount="1.00" name="lemon">2</ingredient>
                    <ingredient amount="0.04" name="jagermeister">13</ingredient>
                    <ingredient amount="0.25" name="red bull">13</ingredient>
                    <ingredient amount="1.00" name="ice cube">30</ingredient>
                </ingredients>
            </bar>
        </date>
    </admin>
</data>
