=== Jadro007/BarUTomaDataAnalyst/database/bar.xsd
<?xml version="1.0"?>

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

<!--

BAR-SCHEMA
<bars>
  <bar owner_id="">
    <name/>
    <bar_id/>
  </bar>
</bars>

-->

    <!-- Simple data types -->
    <xs:simpleType name="idInteger">
        <xs:restriction base="xs:integer">
            <xs:totalDigits value="10"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="nonEmptyString">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Schema -->
    <xs:element name="data">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="bars" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="bar" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="bar_id" type="idInteger"/>
                                        <xs:element name="name" type="nonEmptyString"/>
                                        <xs:element name="info" type="nonEmptyString"/>
                                    </xs:sequence>
                                    <xs:attribute name="owner_id" type="idInteger" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Jadro007/BarUTomaDataAnalyst/database/bar-example.xml
<?xml version="1.0" encoding="UTF-8"?>

<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="bar.xsd">
    <bars>
        <bar owner_id="1">
            <bar_id>1</bar_id>
            <name>Bar U Toma</name>
            <info>This bar is really cool!</info>
        </bar>
        <bar owner_id="2">
            <bar_id>2</bar_id>
            <name>Bar BarBar</name>
            <info>I don't like this bar that much.</info>
        </bar>
    </bars>
</data>
